name: HOTFIX

on:
  pull_request_target:
    branches:
      - main
  workflow_dispatch:


jobs:
    auto-approve:
      runs-on: ubuntu-latest
      if: contains(github.event.pull_request.labels.*.name, 'HOTFIX') && github.event.pull_request.draft == false
      steps:
        - name: Auto-approve
          uses: hmarr/auto-approve-action@v2
          with:
            github-token: "${{ secrets.GITHUB_TOKEN }}"