name: HOTFIX

on:
  pull_request_target:
    branches:
      - main
  workflow_dispatch:


jobs:
    check-label:
      runs-on: ubuntu-latest
      if: contains(github.head_ref, 'hotfix')
      outputs:
        label_added: ${{ steps.add_label.outputs.label_added }}
      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add HOTFIX label
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels \
          --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'Content-Type: application/json' \
          --data '{"labels": ["HOTFIX"]}'
          echo "label_added=true" >> $GITHUB_OUTPUT 

    check-ouputs:
      runs-on: ubuntu-latest
      needs: check-label
      steps:
      - name: check output
        run: |
          echo "${{ needs.check-label.outputs.label_added  }}"
          echo "${{ github.event.pull_request.labels.*.name }}"



    auto-approve:
      runs-on: ubuntu-latest
      needs: check-label
      if: (needs.check-label.outputs.label_added == 'true' || contains(github.event.pull_request.labels.*.name, 'hotfix')) && github.event.pull_request.draft == false
      steps:
        - name: Auto-approve
          uses: hmarr/auto-approve-action@v2
          with:
            github-token: "${{ secrets.GITHUB_TOKEN }}"