name: Slack Review Notifications Workflow

on:
  workflow_call:
    inputs:
      pull_request_number:
        required: true
        type: string

jobs:
  send_notification:
    name: Ping Reviewer(s)
    runs-on: ubuntu-latest
    steps:
      - name: Delay Step
        run: sleep 20
      # Delay to ensure GitHub API has processed all events

      - name: Get Current PR
        id: get_pr
        uses: 8BitJonny/gh-get-current-pr@3.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ github.event_name != 'issue_comment' && github.event.pull_request.head.sha || '' }}

      - name: Checkout code-control-repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/Reusable-Workflow
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Send Slack Notification
        if: ${{ !contains(steps.get_pr.outputs.pr_labels, 'hotfix') }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DM_URL }}
          PR_OBJECT: ${{ steps.get_pr.outputs.pr }}
          GITHUB_ACTOR: ${{ github.actor }}
          PR_URL: ${{ steps.get_pr.outputs.pr_url }}
          PR_NUMBER: ${{ steps.get_pr.outputs.number }}
          PR_INFO: ${{ toJSON(fromJSON(steps.get_pr.outputs.pr)) }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_EVENT_ACTION: ${{ github.event.action }}
          GITHUB_EVENT_REVIEW_STATE: ${{ github.event.review.state }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_LABELS: ${{ toJSON(github.event.review.labels)}}
        shell: bash
        run: python .github/scripts/send_slack_notification.py

      - name: Remove requested changes label
        if: contains(github.event.review.labels, 'requested-changes')
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              label: 'requested-changes'
            });
