name: Reusable Ping Workflow

on:
  workflow_call:
    inputs:
      message:
        description: "Message to be sent as a notification"
        required: true
        type: string

jobs:
  ping:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Debug Message
        run: |
          echo "Message to send: ${{ inputs.message }}"

      - name: Send Notification
        env:
          SLACK_URL: ${{ secrets.SLACK_J_DM_URL }}
          MESSAGE: ${{ inputs.message }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"'"$MESSAGE"'"}' $SLACK_URL
