name: Slack Review Notifications Workflow

on:
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created]
  pull_request:
    types: [review_requested]

jobs:
  send_notification:
    name: Ping Reviewer(s)
    runs-on: ubuntu-latest
    steps:
      - name: Delay Step
        run: sleep 20
        # Delay to ensure GitHub API has processed all events

      - name: Get Current PR
        id: get_pr
        uses: 8BitJonny/gh-get-current-pr@3.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ github.event.pull_request.head.sha }}

      - name: Send Slack Notification
        if: ${{ !contains(steps.get_pr.outputs.pr_labels, 'hotfix') }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_J_DM_URL }}
          PR_OBJECT: ${{ steps.get_pr.outputs.pr }}
          GITHUB_ACTOR: ${{ github.actor }}
          PR_URL: ${{ steps.get_pr.outputs.pr_url }}
          PR_NUMBER: ${{ steps.get_pr.outputs.number }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_EVENT_ACTION: ${{ github.event.action }}
          GITHUB_EVENT_REVIEW_STATE: ${{ github.event.review.state }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: python
        run: |
          import os, json, requests

          # Parse the PR object from the environment variable
          pr_object = json.loads(os.getenv('PR_OBJECT'))

          # Extract requested reviewers
          reviewers = pr_object.get('requested_reviewers', [])

          # Extract PR author
          pr_author = pr_object.get('user', {}).get('login')

          # # Load reviewer JSON data from environment variable
          # reviewers_json = os.getenv('REVIEWERS_JSON')
          # reviewers = json.loads(reviewers_json)

          # Define mapping from GitHub username to Slack user ID
          user_map = {
              'StuartH1': 'U067BG3JC1K',
              'jake94a': 'U03CVABRQNN',
              'zenzenzen': 'U04119RP19C'
          }

          # Loop over each requested reviewer to construct the "mentions" string
          mentions = ' '.join([f"<@{user_map[reviewer['login']]}>"
                               for reviewer in reviewers
                               if reviewer['login'] in user_map])
          print("Mentions: ", mentions) 

          # Get author's Slack ID if available
          author_mention = f"<@{user_map[pr_author]}>" if pr_author in user_map else pr_author
          
          # Determine notification type and construct appropriate message
          notification_type = os.getenv('NOTIFICATION_TYPE', 'review_request')
          
          if notification_type == 'review_request':
              # Original review request notification
              message = f"{mentions} *{os.getenv('GITHUB_ACTOR')}* requested your review on <{os.getenv('PR_URL')}|PR #{os.getenv('PR_NUMBER')}>."
          elif notification_type == 'pr_comment':
              # New comment notification for PR author
              comment_author = os.getenv('COMMENT_AUTHOR')
              message = f"{author_mention} *{comment_author}* commented on your <{os.getenv('PR_URL')}|PR #{os.getenv('PR_NUMBER')}>."
          elif notification_type == 'changes_requested':
              # Changes requested notification for PR author
              reviewer = os.getenv('REVIEWER')
              message = f"{author_mention} *{reviewer}* requested changes on your <{os.getenv('PR_URL')}|PR #{os.getenv('PR_NUMBER')}>."
          
          # Construct the payload to send to Slack
          payload = {
              'text': message,
              'username': 'GitHub Actions',
              'icon_emoji': ':octocat:',
          }

          # Send notification to Slack
          requests.post(os.getenv('SLACK_WEBHOOK_URL'), json=payload)
