name: Reusable daily recap Ping Workflow

on:
  workflow_dispatch: null
  schedule:
    - cron: "0 12 * * *" # Scheduled to run every day

jobs:
  pr-details:
    runs-on: ubuntu-latest
    outputs:
      prDetails: ${{ steps.get-prs.outputs.prDetails }}
    steps:
      - name: Get open PRs
        id: get-prs
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const core = require('@actions/core');
            const dayInMillis = 24 * 60 * 60 * 1000;
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });
            const prDetails = prs.data.map(pr => {
              const ageInDays = Math.round((new Date() - new Date(pr.created_at)) / dayInMillis);
              return `- PR [#${pr.number}](${pr.html_url}) is ${ageInDays} days old.`;  # Format PR details
            }).join('\n');
            core.setOutput("prDetails", prDetails);

  call-reusable-workflow:
    needs: pr-details
    uses: stuartH1/testing-reusable-workflow/.github/workflows/daily-recap.yaml@main
    with:
      prDetails: ${{ needs.pr-details.outputs.prDetails }}
