name: Slack Review Notifications Workflow

on:
  workflow_call:
    inputs:
      pull_request_number:
        required: true
        type: string

jobs:
  send_notification:
    name: Ping Reviewer(s)
    runs-on: ubuntu-latest
    steps:
      - name: Delay Step
        run: sleep 10
        # Delay to ensure GitHub API has processed all events

      - name: Get Current PR
        id: get_pr
        uses: 8BitJonny/gh-get-current-pr@3.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # For issue_comment events, we need to use a different approach
          sha: ${{ github.event_name != 'issue_comment' && github.event.pull_request.head.sha || '' }}
          # For issue_comment events, we'll use the issue number instead
          issue-number: ${{ github.event_name == 'issue_comment' && github.event.issue.number || '' }}

      - name: Send Slack Notification
        if: ${{ !contains(steps.get_pr.outputs.pr_labels, 'hotfix') }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_J_DM_URL }}
          PR_OBJECT: ${{ steps.get_pr.outputs.pr }}
          GITHUB_ACTOR: ${{ github.actor }}
          PR_URL: ${{ steps.get_pr.outputs.pr_url }}
          PR_NUMBER: ${{ steps.get_pr.outputs.number }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_EVENT_ACTION: ${{ github.event.action }}
          GITHUB_EVENT_REVIEW_STATE: ${{ github.event.review.state }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_OBJECT: ${{ toJSON(github.event.issue) }}
        shell: bash
        run: python .github/scripts/send_slack_notification.py
