name: Reusable PR Auto Labeler Workflow

on:
  workflow_call:
    outputs:
      has_hotfix_label:
        description: "Whether the PR has a hotfix label"
        value: ${{ jobs.pr-auto-labeler.outputs.has_hotfix_label }}
      has_requested_changes_label:
        description: "Whether the PR has a requested changes label"
        value: ${{ jobs.pr-auto-labeler.outputs.has_requested_changes_label }}
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [review_requested, opened]

permissions:
  contents: read
  pull-requests: write

jobs:
  review-label-manager:
    name: PR Auto Labeler
    runs-on: ubuntu-latest
    outputs:
      has_requested_changes_label: ${{ steps.set-requested-changes-output.outputs.has_requested_changes_label }}
    if: github.event_name == 'pull_request_review' || github.event_name == 'pull_request'
    steps:
      - name: "Checkout repository: reusable-workflow"
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.WORKFLOWS_SSH_KEY }}
          repository: stuarth1/reusable-workflow
          ref: main
          path: reusable-workflow

      - name: Run labeler
        if: github.event.review.state == 'changes_requested'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['requested-changes']
            });

      - name: Set requested changes output
        id: set-requested-changes-output
        if: contains(steps.run-labeler.outputs.all-labels, 'requested-changes')
        run: |
          echo "has_requested_changes_label=true" >> "$GITHUB_OUTPUT"
