name: Reusable PR Auto Labeler Workflow

on:
  workflow_call:
    outputs:
      has_hotfix_label:
        description: "Whether the PR has a hotfix label"
        value: ${{ jobs.pr-auto-labeler.outputs.has_hotfix_label }}
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [review_requested, opened]

permissions:
  contents: read
  pull-requests: write

jobs:
  review-label-manager:
    name: Manage Review Labels
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_review' || github.event_name == 'pull_request'
    steps:
      - name: "Checkout repository: reusable-workflow"
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.WORKFLOWS_SSH_KEY }}
          repository: stuarth1/reusable-workflow
          ref: main
          path: reusable-workflow
      - name: Add changes requested label
        if: github.event.review.state == 'changes_requested'
        uses: actions/labeler@v5
        with:
          configuration-path: "reusable-workflow/.github/.pr-auto-labeler-config.yaml"
