name: CI Pipeline
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Testing:
    name: Testing
    if: ${{ github.actor != 'dependabot[bot]' }} && ${{ !contains(github.head_ref, 'hotfix') }}
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout repository: ${{ github.repository }}"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          exit 0
