name: CI Pipeline
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  format-and-lint:
    name: Formatting & Linting
    if: contains(github.head_ref, 'hotfix')
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout repository: ${{ github.repository }}"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          pip install black==24.1.1 isort==5.13.2 pycln==2.4.0
      - name: Get list of changed python files in all commits
        id: file_changes
        run: |
          git fetch origin master
          MERGE_BASE=$(git merge-base HEAD origin/master)
          CHANGED_FILES=$(git diff --name-only $MERGE_BASE HEAD | grep '\.py$' || true)
          if [ -z "$CHANGED_FILES" ]; then
            echo "No Python files changed"
          else
            echo "Changed Python files: $CHANGED_FILES"
            echo "::set-output name=files::$CHANGED_FILES"
      - name: Run black checks
        id: black
        if: steps.file_changes.outputs.files
        run: |
          black --check --skip-magic-trailing-comma ${{ steps.file_changes.outputs.files }}
      - name: Run pycln checks
        id: pycln
        if: steps.file_changes.outputs.files
        run: |
          pycln --check --all ${{ steps.file_changes.outputs.files }}
      - name: Run isort checks
        id: isort
        if: steps.file_changes.outputs.files
        run: |
          isort --check --profile=black ${{ steps.file_changes.outputs.files }}
